In [ ]:
#PHASE 1: DATA CLEANING

In [6]:
import pandas as pd
import numpy as np

df=pd.read_excel("Global Superstore.xls",sheet_name="Orders")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [7]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country',
       'Postal Code', 'Market', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')

In [8]:
df.info

<bound method DataFrame.info of        Row ID         Order ID Order Date  Ship Date       Ship Mode  \
0       32298   CA-2012-124891 2012-07-31 2012-07-31        Same Day
1       26341    IN-2013-77878 2013-02-05 2013-02-07    Second Class
2       25330    IN-2013-71249 2013-10-17 2013-10-18     First Class
3       13524  ES-2013-1579342 2013-01-28 2013-01-30     First Class
4       47221     SG-2013-4320 2013-11-05 2013-11-06        Same Day
...       ...              ...        ...        ...             ...
51285   29002    IN-2014-62366 2014-06-19 2014-06-19        Same Day
51286   35398   US-2014-102288 2014-06-20 2014-06-24  Standard Class
51287   40470   US-2013-155768 2013-12-02 2013-12-02        Same Day
51288    9596   MX-2012-140767 2012-02-18 2012-02-22  Standard Class
51289    6147   MX-2012-134460 2012-05-22 2012-05-26    Second Class

      Customer ID     Customer Name      Segment           City  \
0        RH-19495       Rick Hansen     Consumer  New York City
1        JR-16210     Justin Ritter    Corporate     Wollongong
2        CR-12730      Craig Reiter     Consumer       Brisbane
3        KM-16375  Katherine Murray  Home Office         Berlin
4         RH-9495       Rick Hansen     Consumer          Dakar
...           ...               ...          ...            ...
51285    KE-16420   Katrina Edelman    Corporate           Kure
51286    ZC-21910  Zuschuss Carroll     Consumer        Houston
51287    LB-16795    Laurel Beltran  Home Office         Oxnard
51288    RB-19795        Ross Baird  Home Office       Valinhos
51289    MC-18100     Mick Crebagga     Consumer       Tipitapa

                 State  ...        Product ID         Category Sub-Category  \
0             New York  ...   TEC-AC-10003033       Technology  Accessories
1      New South Wales  ...   FUR-CH-10003950        Furniture       Chairs
2           Queensland  ...   TEC-PH-10004664       Technology       Phones
3               Berlin  ...   TEC-PH-10004583       Technology       Phones
4                Dakar  ...  TEC-SHA-10000501       Technology      Copiers
...                ...  ...               ...              ...          ...
51285        Hiroshima  ...   OFF-FA-10000746  Office Supplies    Fasteners
51286            Texas  ...   OFF-AP-10002906  Office Supplies   Appliances
51287       California  ...   OFF-EN-10001219  Office Supplies    Envelopes
51288        São Paulo  ...   OFF-BI-10000806  Office Supplies      Binders
51289          Managua  ...   OFF-PA-10004155  Office Supplies        Paper

                                            Product Name     Sales Quantity  \
0      Plantronics CS510 - Over-the-Head monaural Wir...  2309.650        7
1              Novimex Executive Leather Armchair, Black  3709.395        9
2                      Nokia Smart Phone, with Caller ID  5175.171        9
3                         Motorola Smart Phone, Cordless  2892.510        5
4                         Sharp Wireless Fax, High-Speed  2832.960        8
...                                                  ...       ...      ...
51285                      Advantus Thumb Tacks, 12 Pack    65.100        5
51286  Hoover Replacement Belt for Commercial Guardsm...     0.444        1
51287       #10- 4 1/8" x 9 1/2" Security-Tint Envelopes    22.920        3
51288                            Acco Index Tab, Economy    13.440        2
51289            Eaton Computer Printout Paper, 8.5 x 11    61.380        3

      Discount    Profit  Shipping Cost  Order Priority
0          0.0  762.1845        933.570        Critical
1          0.1 -288.7650        923.630        Critical
2          0.1  919.9710        915.490          Medium
3          0.1  -96.5400        910.160          Medium
4          0.0  311.5200        903.040        Critical
...        ...       ...            ...             ...
51285      0.0    4.5000          0.010          Medium
51286      0.8   -1.1100          0.010          Medium
51287      0.0   11.2308          0.010            High
51288      0.0    2.4000          0.003          Medium
51289      0.0    1.8000          0.002            High

[51290 rows x 24 columns]>

In [11]:
df.describe

<bound method NDFrame.describe of        Row ID         Order ID Order Date  Ship Date       Ship Mode  \
0       32298   CA-2012-124891 2012-07-31 2012-07-31        Same Day
1       26341    IN-2013-77878 2013-02-05 2013-02-07    Second Class
2       25330    IN-2013-71249 2013-10-17 2013-10-18     First Class
3       13524  ES-2013-1579342 2013-01-28 2013-01-30     First Class
4       47221     SG-2013-4320 2013-11-05 2013-11-06        Same Day
...       ...              ...        ...        ...             ...
51285   29002    IN-2014-62366 2014-06-19 2014-06-19        Same Day
51286   35398   US-2014-102288 2014-06-20 2014-06-24  Standard Class
51287   40470   US-2013-155768 2013-12-02 2013-12-02        Same Day
51288    9596   MX-2012-140767 2012-02-18 2012-02-22  Standard Class
51289    6147   MX-2012-134460 2012-05-22 2012-05-26    Second Class

      Customer ID     Customer Name      Segment           City  \
0        RH-19495       Rick Hansen     Consumer  New York City
1        JR-16210     Justin Ritter    Corporate     Wollongong
2        CR-12730      Craig Reiter     Consumer       Brisbane
3        KM-16375  Katherine Murray  Home Office         Berlin
4         RH-9495       Rick Hansen     Consumer          Dakar
...           ...               ...          ...            ...
51285    KE-16420   Katrina Edelman    Corporate           Kure
51286    ZC-21910  Zuschuss Carroll     Consumer        Houston
51287    LB-16795    Laurel Beltran  Home Office         Oxnard
51288    RB-19795        Ross Baird  Home Office       Valinhos
51289    MC-18100     Mick Crebagga     Consumer       Tipitapa

                 State  ...        Product ID         Category Sub-Category  \
0             New York  ...   TEC-AC-10003033       Technology  Accessories
1      New South Wales  ...   FUR-CH-10003950        Furniture       Chairs
2           Queensland  ...   TEC-PH-10004664       Technology       Phones
3               Berlin  ...   TEC-PH-10004583       Technology       Phones
4                Dakar  ...  TEC-SHA-10000501       Technology      Copiers
...                ...  ...               ...              ...          ...
51285        Hiroshima  ...   OFF-FA-10000746  Office Supplies    Fasteners
51286            Texas  ...   OFF-AP-10002906  Office Supplies   Appliances
51287       California  ...   OFF-EN-10001219  Office Supplies    Envelopes
51288        São Paulo  ...   OFF-BI-10000806  Office Supplies      Binders
51289          Managua  ...   OFF-PA-10004155  Office Supplies        Paper

                                            Product Name     Sales Quantity  \
0      Plantronics CS510 - Over-the-Head monaural Wir...  2309.650        7
1              Novimex Executive Leather Armchair, Black  3709.395        9
2                      Nokia Smart Phone, with Caller ID  5175.171        9
3                         Motorola Smart Phone, Cordless  2892.510        5
4                         Sharp Wireless Fax, High-Speed  2832.960        8
...                                                  ...       ...      ...
51285                      Advantus Thumb Tacks, 12 Pack    65.100        5
51286  Hoover Replacement Belt for Commercial Guardsm...     0.444        1
51287       #10- 4 1/8" x 9 1/2" Security-Tint Envelopes    22.920        3
51288                            Acco Index Tab, Economy    13.440        2
51289            Eaton Computer Printout Paper, 8.5 x 11    61.380        3

      Discount    Profit  Shipping Cost  Order Priority
0          0.0  762.1845        933.570        Critical
1          0.1 -288.7650        923.630        Critical
2          0.1  919.9710        915.490          Medium
3          0.1  -96.5400        910.160          Medium
4          0.0  311.5200        903.040        Critical
...        ...       ...            ...             ...
51285      0.0    4.5000          0.010          Medium
51286      0.8   -1.1100          0.010          Medium
51287      0.0   11.2308          0.010            High
51288      0.0    2.4000          0.003          Medium
51289      0.0    1.8000          0.002            High

[51290 rows x 24 columns]>

In [13]:
df.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.sample(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
8584,14709,IT-2011-3203475,2011-02-26,2011-03-04,Standard Class,BO-11425,Bobby Odegard,Consumer,Zaanstad,North Holland,...,FUR-FU-10001086,Furniture,Furnishings,"Advantus Frame, Black",533.376,6,0.2,-0.144,39.260,Medium
38815,2056,US-2013-152072,2013-03-07,2013-03-14,Standard Class,LH-16750,Larry Hughes,Consumer,Salvador,Bahia,...,FUR-CH-10002010,Furniture,Chairs,"Office Star Bag Chairs, Adjustable",46.344,3,0.6,-22.056,2.526,Medium
45876,28632,IN-2012-11812,2012-10-05,2012-10-09,Standard Class,AD-10180,Alan Dominguez,Home Office,Perth,Western Australia,...,OFF-EN-10002007,Office Supplies,Envelopes,"Kraft Clasp Envelope, with clear poly window",22.572,2,0.1,1.452,1.080,Medium
29704,21791,IN-2011-27821,2011-06-21,2011-06-26,Standard Class,JP-16135,Julie Prescott,Home Office,Wuchuan,Guangdong,...,OFF-SU-10003105,Office Supplies,Supplies,"Fiskars Shears, Steel",141.120,3,0.0,25.380,5.620,Medium
15647,20325,IN-2014-29697,2014-10-06,2014-10-06,Same Day,JC-15340,Jasper Cacioppo,Consumer,Rockhampton,Queensland,...,OFF-AR-10004486,Office Supplies,Art,"Sanford Canvas, Blue",136.404,3,0.1,24.174,18.550,High

In [20]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [21]:
df.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
City                      object
State                     object
Country                   object
Postal Code              float64
Market                    object
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority            object
dtype: object

In [22]:
# Order Year
df["Order Year"] = df["Order Date"].dt.year

# Order Month Name
df["Order Month"] = df["Order Date"].dt.month_name()

# Order Quarter
df["Order Quarter"] = df["Order Date"].dt.quarter

# Shipping Days
df["Shipping Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

In [23]:
df[["Order Date", "Ship Date", "Order Year", "Order Month", "Order Quarter", "Shipping Days"]].head()

  Order Date  Ship Date  Order Year Order Month  Order Quarter  Shipping Days
0 2012-07-31 2012-07-31        2012        July              3              0
1 2013-02-05 2013-02-07        2013    February              1              2
2 2013-10-17 2013-10-18        2013     October              4              1
3 2013-01-28 2013-01-30        2013     January              1              2
4 2013-11-05 2013-11-06        2013    November              4              1

In [24]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Order Year,Order Month,Order Quarter,Shipping Days
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,2309.650,7,0.0,762.1845,933.57,Critical,2012,July,3,0
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,3709.395,9,0.1,-288.7650,923.63,Critical,2013,February,1,2
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,5175.171,9,0.1,919.9710,915.49,Medium,2013,October,4,1
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,2892.510,5,0.1,-96.5400,910.16,Medium,2013,January,1,2
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,2832.960,8,0.0,311.5200,903.04,Critical,2013,November,4,1

In [25]:
df.to_csv("Global_Superstore_Cleaned.csv", index=False)